backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: src/img/ 
public_folder: static/img 

collections: 
  - name: "episodes"
    label: "Episodes"    
    delete: true        
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true}
      - { label: "Featured Image", name: "featuredImg", widget: "image" }
      - { label: "Episode No", name: "episodeNo", widget: "number", required: true}
      - { label: "Body", name: "body", widget: "markdown", required: true}
      - { label: "Anchor Link", name: "linkToAnchor", widget: "string", required: true}

